--Create users

CREATE LOGIN [AndrewM] WITH PASSWORD='Travel123'
GO
CREATE USER [AndrewM] FROM LOGIN AndrewM;
GO

CREATE LOGIN [ChrisP] WITH PASSWORD='Travel123'
GO

CREATE USER [ChrisP] FROM LOGIN ChrisP;
GO

CREATE LOGIN [PeterO] WITH PASSWORD='Travel123'
GO
CREATE USER [PeterO] FROM LOGIN PeterO;
GO

CREATE LOGIN [runner] WITH PASSWORD='Travel123'
GO
CREATE USER [runner] FROM LOGIN runner;
GO

